Feature/50
bobocode-labs/gojohnny-rest-api pull request #65
Opened 2018-12-23 16:32 UTC by Shtramak

connect to #50

2018-12-23 18:35 UTC, StanislavZabramnyi approved these changes

2018-12-24 05:22 UTC, tboychuk requested changes

2018-12-24 05:22 UTC, boy4uck commented on src/main/java/co/gojohnny/model/PhotoComment.java
> +    private LocalDateTime creationTime = LocalDateTime.now();
Please add default column value.

2018-12-24 05:22 UTC, boy4uck commented on src/main/resources/db/migration/V1.6__Create_table_photo_comment.sql
> +  creation_time TIMESTAMP    NOT NULL,
Add default value here

2018-12-24 05:45 UTC, tboychuk approved these changes

2018-12-24 05:45 UTC, merged